# -*- coding: utf-8 -*- 
# Problem URL: https://projecteuler.net/problem=29
""" 
 
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 
"""


from time import time

DEBUG = False
PROGRESS = False

def dprint(*args):
    if DEBUG:
        print(*args)
        
def pprint(*args):
    if PROGRESS:
        print(*args)

#------------------------------------------------------------------------------
#---------------------------------- M A I N -----------------------------------
#------------------------------------------------------------------------------

start_time = time()

lower_limit = 2
upper_limit = 100

distinct_terms = set()
for a in range(lower_limit, upper_limit+1):
    for b in range(lower_limit, upper_limit+1):
        distinct_terms.add(a**b)

print(len(distinct_terms))
print('Time:', time() - start_time)